# Generated by Django 3.1.2 on 2021-03-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newCars',
            new_name='newCar',
        ),
        migrations.RenameModel(
            old_name='upcomingCars',
            new_name='upcomingCar',
        ),
    ]
