# Generated by Django 3.1.2 on 2021-03-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210310_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcar',
            name='cardesc',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='upcomingcar',
            name='cardesc',
            field=models.TextField(max_length=500),
        ),
    ]
