# Generated by Django 3.1.2 on 2021-03-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210310_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='listingCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caruserfirstname', models.CharField(max_length=255)),
                ('caruserlastname', models.CharField(max_length=255)),
                ('caruseremail', models.CharField(max_length=255)),
                ('carusermobile', models.CharField(max_length=255)),
                ('caruseraddress', models.TextField(max_length=500)),
                ('carname', models.CharField(max_length=255)),
                ('carmodel', models.CharField(max_length=255)),
                ('cardesc', models.TextField(max_length=500)),
                ('carprice', models.CharField(max_length=255)),
                ('carlaunchdate', models.CharField(max_length=255)),
                ('carmileage', models.CharField(max_length=255)),
                ('carfueltype', models.CharField(max_length=255)),
                ('carcc', models.CharField(max_length=255)),
                ('carseatingcapacity', models.CharField(max_length=255)),
                ('cartransmissiontype', models.CharField(max_length=255)),
                ('carbodytype', models.CharField(max_length=255)),
                ('carimagefront', models.ImageField(upload_to='mylistingcar')),
                ('carimageright', models.ImageField(upload_to='mylistingcar')),
                ('carimageleft', models.ImageField(upload_to='mylistingcar')),
                ('carimageback', models.ImageField(upload_to='mylistingcar')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
