# Generated by Django 3.1.2 on 2021-03-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_listingcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='usedCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=255)),
                ('cardesc', models.TextField(max_length=500)),
                ('carprice', models.CharField(max_length=255)),
                ('carrating', models.CharField(max_length=255)),
                ('carlaunchdate', models.CharField(max_length=255)),
                ('carmileage', models.CharField(max_length=255)),
                ('carfueltype', models.CharField(max_length=255)),
                ('carcc', models.CharField(max_length=255)),
                ('carseatingcapacity', models.CharField(max_length=255)),
                ('cartransmissiontype', models.CharField(max_length=255)),
                ('carbodytype', models.CharField(max_length=255)),
                ('carfrontbrake', models.CharField(max_length=255)),
                ('carrearbrake', models.CharField(max_length=255)),
                ('carfrontsuspension', models.CharField(max_length=255)),
                ('carrearsuspension', models.CharField(max_length=255)),
                ('carsteeringtype', models.CharField(max_length=255)),
                ('carsteeringcolumn', models.CharField(max_length=255)),
                ('carsteeringgeartype', models.CharField(max_length=255)),
                ('carimagefront', models.ImageField(upload_to='myappupcomingcar')),
                ('carimageright', models.ImageField(upload_to='myappupcomingcar')),
                ('carimageleft', models.ImageField(upload_to='myappupcomingcar')),
                ('carimageback', models.ImageField(upload_to='myappupcomingcar')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
