# Generated by Django 3.1.2 on 2021-03-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_usedcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caruserfirstname', models.CharField(max_length=255)),
                ('caruserlastname', models.CharField(max_length=255)),
                ('caruseremail', models.CharField(max_length=255)),
                ('carusermobile', models.CharField(max_length=255)),
                ('caruseraddress', models.TextField(max_length=500)),
                ('carname', models.CharField(max_length=255)),
                ('carmodel', models.CharField(max_length=255)),
                ('carnumber', models.CharField(max_length=255)),
                ('carlaunchdate', models.CharField(max_length=255)),
                ('carimagefront', models.ImageField(upload_to='mylistingcar')),
                ('carimageright', models.ImageField(upload_to='mylistingcar')),
                ('carimageleft', models.ImageField(upload_to='mylistingcar')),
                ('carimageback', models.ImageField(upload_to='mylistingcar')),
                ('date', models.CharField(max_length=255)),
                ('time1', models.CharField(max_length=255)),
                ('time2', models.CharField(max_length=255)),
                ('time3', models.CharField(max_length=255)),
            ],
        ),
    ]
