# Generated by Django 3.1.2 on 2021-03-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210317_1340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appointment1',
        ),
        migrations.DeleteModel(
            name='appointment2',
        ),
    ]
