# Generated by Django 3.1.2 on 2021-05-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('useremail', models.CharField(max_length=255)),
                ('usersubject', models.CharField(max_length=255)),
                ('usermessage', models.TextField(max_length=500)),
            ],
        ),
    ]
